# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ 2022.0.x ]
  pull_request:
    branches: [ 2022.0.x ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - name: Set up JDK 17
      uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde
      with:
        java-version: 17
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f
      with:
        maven-version: 3.8.4
    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven
    - name: Compilation and Installation
      run: bash scripts/build.sh install
    - name: publish coverage report
      run: bash <(curl -s https://codecov.io/bash)
